RedditClone/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:index, :new, :create] do
    get "/content", to: 'posts#content'
  end
  resources :comments
end

RedditClone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text             not null
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :moderator, :title, :description, presence: true
  validates :title, uniqueness: true

  belongs_to(:moderator,
    class_name: "User",
    inverse_of: :subs)

  has_many(
    :post_subs,
    dependent: :destroy,
    inverse_of: :sub
  )

  has_many(
    :posts,
    through: :post_subs,
    dependent: :destroy
    )
end

RedditClone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :moderator?, only: [:edit, :update]

  def new
    @sub = Sub.new
  end

  def create
    @sub = current_user.subs.new(sub_params)

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    render :edit
  end

  def update

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def index
    @subs = Sub.all #may need to include
  end

  def show
    @sub = Sub.find(params[:id])
    @posts = Post.joins(:post_subs).where('post_subs.sub_id = ?', @sub.id)
  end

  def moderator?
    @sub = Sub.find(params[:id])
    redirect_to subs_url unless current_user.id == @sub.moderator_id
  end

  def destroy
    @sub = Sub.find(params[:id])
    @sub.destroy
    redirect_to subs_url
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

RedditClone/app/helpers/subs_helper.rb
module SubsHelper
end

RedditClone/app/views/subs/_form.html.erb
<% header = @sub.persisted? ? "Edit" : "New sub form!" %>
<% action = @sub.persisted? ? sub_url(@sub) : subs_url %>
<% method = @sub.persisted? ? "patch" : "post" %>
<% button = @sub.persisted? ? "Update" : "Submit" %>

<h1><%= header %></h1>
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" method="<%= method %>">
  <%= auth_token %>

  <label for="sub_title">Title</label>
  <input type="text" name="sub[title]" value="<%= @sub.title %>" id="sub_title">

  <br>
  <label for="sub_description">Description</label><br>
  <textarea name="sub[description]" rows="20" cols="40"><%= @sub.description %></textarea>

  <br>
  <input type="submit" value="<%= button %>">
</form>

RedditClone/app/views/subs/edit.html.erb
<%= render "form" %>

RedditClone/app/views/subs/index.html.erb
<h1>All the subs</h1>

<ul>
  <% @subs.each do |sub| %>
  <li> <%= link_to sub.title, sub_url(sub) %> </li>
  <% end %>
</ul>

<%= link_to "Create new sub", new_sub_url %>

RedditClone/app/views/subs/new.html.erb
<%= render 'form' %>

RedditClone/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

Description:<br>
<%= @sub.description %>
<br>
<br>
Posts:
<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_url(post) %></li>
  <% end %>
</ul>

<p>
  <%= link_to "New Post", new_sub_post_url(@sub) %>
  <br>
  <% if current_user.id == @sub.moderator_id %>
    <%= (link_to "Edit", edit_sub_url(@sub)) %>
    <br>
    <%= button_to "Delete", sub_url(@sub), method: :delete %>
  <% end %>
  <%= link_to "Back", subs_url %>
</p>