Music App/config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:create, :destroy, :update]
end

Music App/app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  note       :text             not null
#  user_id    :integer          not null
#  track_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Note < ActiveRecord::Base
  validates :user_id, :track_id, :note, presence: true

  belongs_to :user
  belongs_to :track
end

Music App/app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.save
    redirect_to track_url(@note.track_id)
  end

  def update

  end

  def destroy
    @note = Note.find_by(id: params[:id])
    @track_id = @note.track_id
    if current_user.id == @note.user_id
      @note.destroy
      redirect_to track_url(@track_id)
    else
      head: 403
    end
  end

  private

  def note_params
    params.require(:note).permit(:user_id, :track_id, :note)
  end

end

Music App/app/helpers/notes_helper.rb
module NotesHelper
end

Music App/app/views/notes/_form.html.erb
<form action="<%= notes_url %>" method="POST">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <input type="hidden" name="note[track_id]" value="<%=track_id%>">

  <label for="note_note">Your thoughts:</label>
  <br>
  <textarea name="note[note]"
            id="note_note"
            rows="15"
            cols="15"></textarea>
  <br>
  <input type="submit"  value="Post">
  <br>

</form>

Music App/app/views/notes/_note.html.erb
<%= note.user.email %> says...
<br>
<%= note.note %>
<%= (button_to "Delete", note_url(note), method: :delete) if current_user.id == note.user.id %>
<br>
<br>