RedditClone/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:new, :create]
  end
  resources :posts, except: [:index, :new, :create] do
    get "/content", to: 'posts#content'
  end
  resources :comments
end

RedditClone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text             not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  validates :title, :content, :subs, :author, presence: true

  belongs_to(
    :author,
    class_name: :User,
    inverse_of: :posts
  )

  has_many(
    :post_subs,
    dependent: :destroy,
    inverse_of: :post
  )

  has_many :total_comments

  has_many :comments, as: :commentable

  has_many :subs, through: :post_subs
end

RedditClone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :author?, only: [:edit, :update, :destroy]

  def edit
    @post = Post.find(params[:id])
    @subs = Sub.all

  end

  def update
    @post = Post.find(params[:id])
    @subs = Sub.all
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @sub = @post.sub_id
    @post.destroy
    redirect_to sub_url(@sub)
  end

  def create
    @post = current_user.posts.new(post_params)
    @subs = Sub.all
    if @post.save
      redirect_to post_content_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def new
    @post = Post.new
    @subs = Sub.all
  end

  def show
    @post = Post.find(params[:id])
    if @post.url.nil? || @post.url.empty?
      @comments = @post.comments#.includes(:child_comments)
      render :content
    else
      redirect_to @post.url
    end
  end

  def content
    @post = Post.find(params[:post_id])
    @comments = @post.comments#.includes(:child_comments)
    render :content
  end

  private
  def author?
    @post = Post.find(params[:id])

    unless current_user.id == @post.author_id
      redirect_to sub_url(@post.id)
    end
  end

  def post_params
    params.require(:post).permit(:title, :content, :url, sub_ids: [])
  end
end

RedditClone/app/helpers/posts_helper.rb
module PostsHelper
end

RedditClone/app/views/posts/_child.html.erb
<%= child.author.username %> says:
<br>
<%= child.content %>
<br>
<%= link_to "view comment", comment_url(child) %>
<br>
<% child.comments.each do |comment| %>
  <%= render "child", child: comment  %>
  <br>
<% end %>
<br>

RedditClone/app/views/posts/_form.html.erb
<% header = @post.persisted? ? "Edit" : "New post!" %>
<% action = @post.persisted? ? post_url(@post) : sub_posts_url(params[:sub_id]) %>
<% method = @post.persisted? ? "patch" : "post" %>
<% button = @post.persisted? ? "Update" : "Submit" %>

<h1><%= header %></h1>
<form action="<%= action %>" method="post">
  <input type="hidden" name="_method" value="<%= method %>">
  <%= auth_token %>

  <label for="post_title">Title</label>
  <input type="text" name="post[title]" value="<%= @post.title %>" id="post_title">
  <br>

  <label for="post_url">URL</label>
  <input type="text" name="post[url]" value="<%= @post.url %>">

  <br>
  <input type="hidden" name="post[sub_ids][]" value="">
  <label for="post_subs">Subs</label>
    <% @subs.each do |subb| %>
      <input type="checkbox"
             name="post[sub_ids][]"
             value="<%=subb.id%>"
             <%= "checked" if @post.sub_ids.include?(subb.id) %>>
          <%= subb.title %>
      <% end %>

  <br>
  <label for="post_content">Content</label><br>
  <textarea name="post[content]" rows="20" cols="40" id="post_content"><%= @post.content %></textarea>

  <br>
  <input type="submit" value="<%= button %>">
</form>

RedditClone/app/views/posts/_posts.html.erb
<h3> <%=post.title%> </h3>

<p>
  <%= post.content %>
</p>

<p>
  <%= (link_to "Edit", edit_post_url(post)) if current_user == post.author %>
</p>

RedditClone/app/views/posts/content.html.erb
<h3> <%=@post.title%> </h3>

<p>
  <%= @post.content %>
</p>

<p>
  Comments:
</p>

<form action="<%= comments_url%>" method="post">
  <%= auth_token %>

  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
  <input type="hidden" name="comment[commentable_id]" value="<%= @post.id %>">
  <input type="hidden" name="comment[commentable_type]" value="Post">

  <label for="comment_content">Your thoughts</label>
  <br>
  <textarea name="comment[content]"></textarea>
    <br>
  <input type="submit" value="Comment!">
</form>
<br>

<% @comments.each do |comment| %>
  <%= render 'child', child: comment %>
<% end %>

<p>
  <% if current_user == @post.author %>
    <%= (link_to "Edit", edit_post_url(@post))  %>
    <br>
    <%= button_to "Delete", post_url(@post) ,method: :delete%>
    <br>
  <% end %>

  <%= link_to "Back", subs_url %>
</p>

RedditClone/app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

RedditClone/app/views/posts/new.html.erb
<%= render 'form', post: @post %>