Music App/config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :new, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:create, :destroy, :update]
end

Music App/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  album_id   :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  style      :string           not null
#  lyrics     :text             not null
#

class Track < ActiveRecord::Base
  validates :album_id, :name, :style, presence: true
  validates :style, inclusion: ["REGULAR", "BONUS"]

  has_many :notes, dependent: :destroy

  belongs_to :album
  has_one :band, through: :album, source: :band
end

Music App/app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :log_in_check
  
  def show
    @track = Track.find_by(id: params[:id])

    render :show
  end

  def new
    @track = Track.new
    @album = Album.find(params[:album_id])
    @albums = Album.all
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.valid?
      @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      @albums ||= Album.all
      render :new
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])
    @album_id = @track.album_id
    @albums = Album.all
    render :edit
  end

  def update
    @track = Track.find_by(id: params[:id])

    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      @album_id ||= @track.album_id
      @albums ||= Album.all
      flash.now[errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find_by(id: params[:id])
    @album = @track.album_id
    @track.destroy
    redirect_to album_url(@album)
  end

  private
  def track_params
    params.require(:track).permit(:name, :album_id, :style, :lyrics)
  end
end

Music App/app/helpers/tracks_helper.rb
module TracksHelper
  def lyric_helper(text)
    lines = text.split("\n")
    lines.map! { |line| "♫ " + line }
    newlines =  "<pre>#{lines.join("\n")}</pre>"
    newlines.html_safe
  end

end

Music App/app/views/tracks/edit.html.erb
<h1>Edit <%= @track.name %></h1>

<form action="<%= track_url(@track) %>"" method="POST">
  <input type="hidden" name="_method" value="PATCH">

  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

     <label for="track_album_id">Album</label>
     <select name="track[album_id]" id="track_album_id">
       <% @albums.each do |album| %>
         <option value="<%= album.id %>"
           <%= "selected" if album.id == @album_id %>><%= album.title %></option>
       <% end %>
     </select>
     <br>

     <label for="track_style">Style</label>
       <br>
       <input type="radio" name="track[style]" value="BONUS">Bonus
       <input type="radio" name="track[style]" value="REGULAR">Regular
       <br>

     <label for="track_name">Name</label>
       <input type="text"
              name="track[name]"
              id="track_name"
              value="<%= @track.name %>">
      <br>

     <label for="track_lyrics">Lyrics</label>
     <br>
       <textarea name="track[lyrics]" rows="20" cols="50"><%= @track.lyrics %></textarea>
       <br>

     <input type="submit" value="Submit!">

   </form>

Music App/app/views/tracks/new.html.erb
<h1>Adding a new track</h1>

<form action="/tracks" method="POST">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

     <label for="track_album_id">Album</label>
     <select name="track[album_id]" id="track_album_id">
       <% @albums.each do |album| %>
         <option value="<%= album.id %>"
           <%= "selected" if album.id == @album.id %>><%= album.title %></option>
       <% end %>
     </select>
     <br>

     <label for="track_style">Style</label>
       <br>
       <input type="radio" name="track[style]" value="BONUS">Bonus
       <input type="radio" name="track[style]" value="REGULAR">Regular
       <br>

     <label for="track_name">Name</label>
       <input type="text"
              name="track[name]"
              id="track_name"
              value="<%= @track.name %>">
      <br>

     <label for="track_lyrics">Lyrics</label>
     <br>
       <textarea name="track[lyrics]" rows="20" cols="50"><%= @track.lyrics %></textarea>
       <br>

     <input type="submit" value="Add new track!">

   </form>

Music App/app/views/tracks/show.html.erb
<h1> <%= @track.name %> </h1>

<%= button_to "Edit", edit_track_url(@track), method: :get %>


<p> <%= @track.style %> TRACK </p>

<p> Lyrics </p>

<p><%= lyric_helper(@track.lyrics) %></p>



<%= button_to "DELETE TRACK!?", track_url(@track), method: :delete %>
<%= button_to "Back", album_url(@track.album_id), method: :get %>

<p>Comments</p>
<br>
<% @track.notes.each do |note| %>
  <%= render "notes/note", note: note %>
<% end %>
<br>
<%= render "notes/form", track_id: params[:id] %>